[project]
name = "example"
version = "0.1.0"
description = "Example project for pixi-kernel"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = "3.12.*"
ipykernel = "6.*" # It is necessary to install the ipykernel to be able to use pixi-kernel
